// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package router

import (
	"github.com/zbd20/fiber-demo/internal/biz"
	"github.com/zbd20/fiber-demo/internal/conf"
	"github.com/zbd20/fiber-demo/internal/db"
	"github.com/zbd20/fiber-demo/internal/services"
)

// Injectors from wire.go:

func InitRouter() (*Router, error) {
	app := NewFiber()
	config := conf.GetConfig()
	gormDB, err := db.NewMySQLClient(config)
	if err != nil {
		return nil, err
	}
	baseService, err := services.NewBaseService(gormDB)
	if err != nil {
		return nil, err
	}
	baseController := biz.NewBaseController(app, baseService)
	router := NewRouter(baseController)
	return router, nil
}
